services:
  - type: web
    name: node-sentinel-api
    runtime: docker
    dockerfilePath: ./Dockerfile
    dockerContext: .
    region: oregon
    plan: free
    envVars:
      - key: KEEP_ALIVE_INTERVAL_SECONDS
        value: "600"
      - key: OCR_ENABLED
        value: "true"
      - key: TESSERACT_CMD
        value: "/usr/bin/tesseract"
